### ISSUE TITLE
onigurumacffi lacks pre-build wheels for arm64 and python 3.11 and 3.12

### ISSUE THREAD

**Issue by ssbarnea** [asottile/onigurumacffi#178]
It would be very useful if onigurumacffi CI/CD pipelines would be extended to produce pre-build wheels for command platform. Looking at them they seem to work only for quite old versions of python and on linux only for amd64, missing arm64.

With GHA now also being able to use arm64 linux builders, it should not be too hard to also produce these.

Would you consider a contribution that would extend these?

**Comment by asottile** [comment]
gha doesn't yet without paying and I'm not doing that (or emulating)

**Comment by asottile** [comment]
you're also confused: they are abi3 wheels
